Cray_Lib.Data:Register('Cray_Basewars.Data.Money', 'number')
Cray_Lib.Data:Register('Cray_Basewars.Data.Level', 'number')
Cray_Lib.Data:Register('Cray_Basewars.Data.Exp', 'number')
Cray_Lib.Data:Register('Cray_Basewars.Data.Prestige', 'number')
Cray_Lib.Data:Register('Cray_Basewars.Data.Faction', 'string')