AddCSLuaFile('cl_init.lua')
AddCSLuaFile('shared.lua')
include('shared.lua')

include('shared/base.lua')
AddCSLuaFile('shared/base.lua')
include('shared/language.lua')
AddCSLuaFile('shared/language.lua')
include('server/base.lua')
include('server/functions.lua')
include('server/player.lua')
AddCSLuaFile('client/player.lua')
AddCSLuaFile('client/nets.lua')
include('server/nets.lua')